Added yaw/pitch property
DynamXInc/DynamX pull request #13
Opened 2022-09-25 20:44 UTC by Ertinox45

2022-09-25 21:01 UTC, YanisBDF requested changes

2022-09-25 21:01 UTC, YanisBDF commented on src/main/java/fr/dynamx/common/contentpack/parts/PartSeat.java
> +    public boolean limitFieldOfView() {
shouldLimitFieldOfView* plus explicite

2022-09-25 21:01 UTC, YanisBDF commented on src/main/java/fr/dynamx/common/contentpack/parts/PartSeat.java
> +    public float getMaxYaw() {
Utilise des @Getter please

2022-09-25 21:01 UTC, YanisBDF commented on src/main/java/fr/dynamx/client/renders/RenderPhysicsEntity.java
> +                    if(seat.limitFieldOfView()) ((AbstractClientPlayer) e).renderYawOffset = ((AbstractClientPlayer) e).prevRenderYawOffset = 0;
On n'utilise pas les condition sur une ligne et les conditions sans accolades. Tu peux regler ça please ?

2022-09-26 11:05 UTC, YanisBDF requested changes

2022-09-26 11:05 UTC, YanisBDF commented on src/main/java/fr/dynamx/client/camera/CameraSystem.java
> +            if(seat != null){
Inverse le null check please

2022-09-26 11:05 UTC, YanisBDF commented on src/main/java/fr/dynamx/client/camera/CameraSystem.java
> +                if(Minecraft.getMinecraft().gameSettings.thirdPersonView > 0){
Il y a ClientEventHandler.MC

2022-09-26 11:05 UTC, YanisBDF commented on src/main/java/fr/dynamx/client/camera/CameraSystem.java
> +                }else{
Reformat le code please

2022-09-26 11:05 UTC, YanisBDF commented on src/main/java/fr/dynamx/client/camera/CameraSystem.java
> +        Vector3f eye = Vector3fPool.get(0, f + (Minecraft.getMinecraft().gameSettings.thirdPersonView > 0 ? cameraPositionY : 0), 0);
Idem ClientEventHandler.MC

2022-09-26 12:53 UTC, YanisBDF requested changes

2022-09-26 12:53 UTC, YanisBDF commented on src/main/java/fr/dynamx/client/camera/CameraSystem.java
> +            }else{
Si tu fais un return ca sert a rien de faire un "else"

2022-09-26 13:00 UTC, Ertinox45 commented on src/main/java/fr/dynamx/client/camera/CameraSystem.java
> +            }else{
Ah oui merde j'suis trop con

2022-09-27 20:15 UTC, AymericBdy commented on src/main/java/fr/dynamx/client/camera/CameraSystem.java
> +            cameraPositionY = ClientEventHandler.MC.gameSettings.thirdPersonView > 0 ? seat.getCameraPositionY() : 0;
Fais un vrai if et appeles le translate que si cameraPositionY != 0 :
if(ClientEventHandler.MC.gameSettings.thirdPersonView > 0 && seat.getCameraPositionY() != 0)

2022-09-27 20:15 UTC, AymericBdy commented on src/main/java/fr/dynamx/client/renders/RenderPhysicsEntity.java
> +                    if(seat.shouldLimitFieldOfView()) {
mettre les deux conditions dans le même if

2022-09-27 20:15 UTC, AymericBdy commented on src/main/java/fr/dynamx/common/contentpack/parts/PartSeat.java
> +
Ligne vide mal placée (oui je chipote :)

2022-09-27 21:19 UTC, merged

2022-09-27 21:19 UTC, AymericBdy commented
Merci pour la contribution !