Features and Fix
DynamXInc/DynamX pull request #4
Opened 2022-08-07 21:20 UTC by Ertinox45

Features: Player position on seat (Standing, Sit, Sleeping), PlayerStandOnTop(always, progressive, never) property, Material (block) property,
Fix : generation of the lang file (en_us and en_US)

2022-08-08 14:48 UTC, YanisBDF commented
Tu devrais utiliser les DefinitionType pour les Properties que t'as rajouté. C'est pas génial de check avec des string, comme tu peux le voir on fait jamais ou très rarement ça. 
Pour les null check etc, au lieu de tout mettre a l'intérieur de la condition je te conseille d'utiliser des null check avec return. Comme ce que tu as fait dans ton dernier commit. 
Please, supprime la fonction getMat. Je suis désolé mais c'est vraiment sale et t'as juste à utilisé "valueOf" une fonction disponible de base dans toute les enums. 
Enfin, j'aime beaucoup tes idées de features. Merci beaucoup. Il faudrait juste que tu améliores ton code avec les conseils que je t'ai donné pour qu'on accepte ta pull request.

2022-08-08 17:16 UTC, AymericBdy requested changes

2022-08-08 17:16 UTC, AymericBdy commented on src/main/java/fr/dynamx/utils/DynamXUtils.java
> +    public static Material getMat(String s)
A renommer en getMaterial(String name)

2022-08-08 17:16 UTC, AymericBdy commented on src/main/java/fr/dynamx/utils/DynamXUtils.java
> +        if(s.equals("AIR"))
horrible
Je suggère soit de faire un switch soit de faire
`           private static final List<String> MATERIAL_NAMES = Arrays.asList("AIR", "ANVIL", "BARRIER", "CACTUS", "CAKE");
            private static final Material[] MATERIALS = new Material[] {Material.AIR, Material.ANVIL, Material.BARRIER, Material.CACTUS, Material.CAKE};
//...
            return MATERIALS[MATERIAL_NAMES.indexOf("CACTUS")];`

2022-08-08 18:09 UTC, Ertinox45 commented on src/main/java/fr/dynamx/client/handlers/ClientEventHandler.java
> +            if(DynamXContext.getWalkingPlayers().containsKey(entityPlayer)){
Hm, c'est purement théorique j'ai pas testé mais étant donné qu'il y a le mode "progressive" qui se désactive à une vitesse > 30km/h, ça veut dire qu'en dessous de 30km/h le walking player sera déjà activé, et il ne s'active que lorsque le joueur arrive ou bouge, donc si le joueur reste à sa position sans bouger, il ne tombera pas à une vitesse > 30km/h non ?

2022-08-19 13:36 UTC, AymericBdy commented on src/main/java/fr/dynamx/client/handlers/ClientEventHandler.java
> +            if(DynamXContext.getWalkingPlayers().containsKey(entityPlayer)){
Hum oui en effet bien vu ^^
Bah du coup oui laisses cette condition, mais ça serait bien d'en ajouter une pour empêcher qu'il s'active > 30 km/h aussi.

2022-08-19 22:30 UTC, AymericBdy approved these changes
Merci pour ta PR :)

2022-08-19 22:39 UTC, merged